version: "3.9"
services:
  api:
    build: .
    container_name: todo-api
    ports:
      - "8000:8000"
    environment:
      - DATA_FILE=/data/tasks.json
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL_SECONDS=60
    volumes:
      - data:/data
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  data: {}
